/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background:               'var(--bg-surface)',
        surface:                  'var(--bg-surface)',
        'surface-container':      'var(--bg-card)',
        'surface-container-low':  'var(--bg-card)',
        'surface-container-high': 'var(--bg-card-hover)',
        'surface-container-highest': 'var(--bg-overlay)',
        'surface-bright':         'var(--bg-card-hover)',
        'on-background':          'var(--text-primary)',
        'on-surface':             'var(--text-primary)',
        'on-surface-variant':     'var(--text-secondary)',
        primary:                  'rgb(var(--accent-rgb) / <alpha-value>)',
        'primary-container':      '#8083ff',
        'on-primary':             '#ffffff',
        'on-primary-container':   '#0d0096',
        'inverse-primary':        '#494bd6',
        outline:                  'var(--border-mid)',
        'outline-variant':        'var(--border-subtle)',
        error:                    '#ff7f50',
        'error-container':        '#93000a',
        secondary:                '#ffb59c',
        tertiary:                 '#ffb783',
      },
      fontFamily: {
        sans:    ['Inter', 'sans-serif'],
        display: ['Hanken Grotesk', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'title-md':  ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg':   ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':   ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':  ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm':  ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '9999px',
      },
      spacing: {
        xs:   '4px',
        sm:   '12px',
        md:   '24px',
        lg:   '48px',
        xl:   '80px',
        gutter: '24px',
      },
    },
  },
  plugins: [],
}
