const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('golem', {
  db: {
    listConversations:         ()                              => ipcRenderer.invoke('db:listConversations'),
    listProjectConversations:  (projectId)                    => ipcRenderer.invoke('db:listProjectConversations', projectId),
    getConversation:           (id)                           => ipcRenderer.invoke('db:getConversation', id),
    createConversation:        (title, model, sigilId, projectId, skillId) => ipcRenderer.invoke('db:createConversation', title, model, sigilId, projectId, skillId),
    renameConversation:        (id, title)                    => ipcRenderer.invoke('db:renameConversation', id, title),
    deleteConversation:        (id)                           => ipcRenderer.invoke('db:deleteConversation', id),
    pinConversation:           (id)                           => ipcRenderer.invoke('db:pinConversation', id),
    unpinConversation:         (id)                           => ipcRenderer.invoke('db:unpinConversation', id),
    getMessages:               (convId)                       => ipcRenderer.invoke('db:getMessages', convId),
    addMessage:                (convId, role, content)        => ipcRenderer.invoke('db:addMessage', convId, role, content),
    updateMessage:             (id, content)                  => ipcRenderer.invoke('db:updateMessage', id, content),
    deleteMessage:             (id)                           => ipcRenderer.invoke('db:deleteMessage', id),
    getSetting:                (key, fallback)                => ipcRenderer.invoke('db:getSetting', key, fallback),
    setSetting:                (key, value)                   => ipcRenderer.invoke('db:setSetting', key, value),

    listSigils:    ()                      => ipcRenderer.invoke('db:listSigils'),
    createSigil:   (name, content)         => ipcRenderer.invoke('db:createSigil', name, content),
    updateSigil:   (id, name, content)     => ipcRenderer.invoke('db:updateSigil', id, name, content),
    deleteSigil:   (id)                    => ipcRenderer.invoke('db:deleteSigil', id),

    listSkills:    ()                                         => ipcRenderer.invoke('db:listSkills'),
    getSkill:      (id)                                       => ipcRenderer.invoke('db:getSkill', id),
    createSkill:   (name, category, sysPrompt, starter)       => ipcRenderer.invoke('db:createSkill', name, category, sysPrompt, starter),
    updateSkill:   (id, name, category, sysPrompt, starter)   => ipcRenderer.invoke('db:updateSkill', id, name, category, sysPrompt, starter),
    deleteSkill:   (id)                                       => ipcRenderer.invoke('db:deleteSkill', id),

    getTelemetrySummary:      ()           => ipcRenderer.invoke('db:getTelemetrySummary'),

    listProjects:             ()           => ipcRenderer.invoke('db:listProjects'),
    createProject:            (name)       => ipcRenderer.invoke('db:createProject', name),
    renameProject:            (id, name)   => ipcRenderer.invoke('db:renameProject', id, name),
    deleteProject:            (id)         => ipcRenderer.invoke('db:deleteProject', id),
    setProjectDirectory:      (id, dirPath)           => ipcRenderer.invoke('db:setProjectDirectory', id, dirPath),
    setProjectNumCtx:         (id, numCtx)            => ipcRenderer.invoke('db:setProjectNumCtx', id, numCtx),
    syncProjectDirectory:     (projectId, dirPath)    => ipcRenderer.invoke('project:syncDirectory', projectId, dirPath),
    listProjectFiles:         (projectId)  => ipcRenderer.invoke('db:listProjectFiles', projectId),
    addProjectFile:           (projectId, name, content) => ipcRenderer.invoke('db:addProjectFile', projectId, name, content),
    removeProjectFile:        (id)         => ipcRenderer.invoke('db:removeProjectFile', id),
  },
  memory: {
    load: ()        => ipcRenderer.invoke('memory:load'),
    save: (content) => ipcRenderer.invoke('memory:save', content),
  },
  dialog: {
    openFile:      ()     => ipcRenderer.invoke('dialog:openFile'),
    saveFile:      (opts) => ipcRenderer.invoke('dialog:saveFile', opts),
    openDirectory: ()     => ipcRenderer.invoke('dialog:openDirectory'),
  },
  application: {
    getLoginItemEnabled: ()       => ipcRenderer.invoke('app:getLoginItemEnabled'),
    setLoginItem:        (enable) => ipcRenderer.invoke('app:setLoginItem', enable),
  },
  ollama: {
    listModels:      ()        => ipcRenderer.invoke('ollama:listModels'),
    ensureRunning:   ()        => ipcRenderer.invoke('ollama:ensureRunning'),
    pullModel:       (name)    => ipcRenderer.invoke('ollama:pullModel', name),
    deleteModel:     (name)    => ipcRenderer.invoke('ollama:deleteModel', name),
    startStream:     (payload) => ipcRenderer.invoke('ollama:startStream', payload),
    stopStream:      ()        => ipcRenderer.send('ollama:stopStream'),
    onChunk:         (cb)      => ipcRenderer.on('ollama:chunk', (_, chunk) => cb(chunk)),
    onStreamEnd:     (cb)      => ipcRenderer.on('ollama:streamEnd', (_, err) => cb(err)),
    offChunk:        ()        => ipcRenderer.removeAllListeners('ollama:chunk'),
    offStreamEnd:    ()        => ipcRenderer.removeAllListeners('ollama:streamEnd'),
    onPullProgress:  (cb)      => ipcRenderer.on('ollama:pullProgress', (_, data) => cb(data)),
    offPullProgress: ()        => ipcRenderer.removeAllListeners('ollama:pullProgress'),
    onToolCallStart:  (cb)     => ipcRenderer.on('ollama:tool_call_start', (_, payload) => cb(payload)),
    onToolCallResult: (cb)     => ipcRenderer.on('ollama:tool_call_result', (_, payload) => cb(payload)),
    offToolCallStart:  ()      => ipcRenderer.removeAllListeners('ollama:tool_call_start'),
    offToolCallResult: ()      => ipcRenderer.removeAllListeners('ollama:tool_call_result'),
    testToolCapability: (model) => ipcRenderer.invoke('ollama:testToolCapability', model),
    getToolCapability:  (model) => ipcRenderer.invoke('ollama:getToolCapability', model),
  },
  window: {
    setSize:           (w, h) => ipcRenderer.send('window:setSize', w, h),
    minimize:          ()     => ipcRenderer.send('window:minimize'),
    maximize:          ()     => ipcRenderer.send('window:maximize'),
    close:             ()     => ipcRenderer.send('window:close'),
    isMaximized:       ()     => ipcRenderer.invoke('window:isMaximized'),
    onMaximizeChange:  (cb)   => ipcRenderer.on('window:maximizeChange', (_, v) => cb(v)),
    offMaximizeChange: ()     => ipcRenderer.removeAllListeners('window:maximizeChange'),
  },
})
